// Office Generator (spec §6).
//
// Real document generation. The Agent first asks the LLM to produce a structured
// outline (AI → Outline → Content), then we render a genuine .pptx / .xlsx /
// .docx file with the appropriate library and save it to the output directory.
// Every tool is LOW risk, so presentations/documents generate and open
// automatically.

import fs from "node:fs";
import path from "node:path";
import PptxGenJS from "pptxgenjs";
import ExcelJS from "exceljs";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { registerTool } from "../registry";
import { ok, fail, notConfigured } from "../permissions";
import { runLordText, runLordJson } from "../llm";
import { getLordConfig } from "../config";
import type { ToolContext, ToolResult } from "../types";

function safeName(topic: string): string {
  const base = topic
    .replace(/[^a-zA-Z0-9 _-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 60);
  return base || "Lord_Document";
}

async function writeOut(
  name: string,
  ext: string,
  buffer: Buffer | Uint8Array | string,
): Promise<string> {
  const dir = getLordConfig().outputDir;
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${name}.${ext}`);
  fs.writeFileSync(file, buffer as Buffer);
  return file;
}

interface SlideSpec {
  heading: string;
  bullets: string[];
}
interface DeckSpec {
  title: string;
  subtitle?: string;
  slides: SlideSpec[];
}

export function registerOfficeTools(): void {
  registerTool({
    name: "office.powerpoint",
    category: "office",
    description: "Create a PowerPoint presentation about a topic. Generates a real .pptx file.",
    risk: "low",
    requiresConfirmation: false,
    parameters: [
      { name: "topic", type: "string", description: "Subject of the presentation", required: true },
      {
        name: "slides",
        type: "number",
        description: "Approximate number of slides",
        required: false,
      },
    ],
    examples: ["Create a 10-slide presentation about Newton's Prism Experiment."],
    async execute(params, ctx: ToolContext): Promise<ToolResult> {
      const topic = String(params.topic ?? "Untitled");
      const slideCount = Math.min(Math.max(Number(params.slides ?? 8), 3), 20);
      let spec: DeckSpec;
      try {
        ctx.log({ level: "info", source: "office", message: `Planning presentation: ${topic}` });
        spec = await runLordJson<DeckSpec>({
          system: "You are a presentation designer. Produce a clear, well-structured slide deck.",
          prompt: `Create an outline for a ${slideCount}-slide presentation titled appropriately about: ${topic}. Return JSON with keys: title (string), subtitle (string|null), slides (array of {heading:string, bullets:string[]}).`,
          schemaHint:
            '{ "title": string, "subtitle": string|null, "slides": [{"heading": string, "bullets": string[]}] }',
          mode: "creative",
        });
        if (!spec?.slides?.length) throw new Error("empty");
      } catch {
        spec = {
          title: topic,
          subtitle: "Generated by LORD",
          slides: Array.from({ length: slideCount }, (_, i) => ({
            heading: `Slide ${i + 1}: ${topic}`,
            bullets: ["Key point one.", "Key point two.", "Key point three."],
          })),
        };
      }

      try {
        const pptx = new PptxGenJS();
        const titleSlide = pptx.addSlide();
        titleSlide.addText(spec.title, {
          x: 0.5,
          y: 2.2,
          w: 9,
          h: 1.2,
          fontSize: 36,
          bold: true,
          color: "1F2A44",
        });
        if (spec.subtitle)
          titleSlide.addText(spec.subtitle, {
            x: 0.5,
            y: 3.4,
            w: 9,
            h: 0.8,
            fontSize: 18,
            color: "555555",
          });
        for (const s of spec.slides) {
          const slide = pptx.addSlide();
          slide.addText(s.heading, {
            x: 0.5,
            y: 0.4,
            w: 9,
            h: 0.9,
            fontSize: 26,
            bold: true,
            color: "1F2A44",
          });
          slide.addText(
            s.bullets.map((b) => ({ text: b, options: { bullet: true } })),
            { x: 0.7, y: 1.5, w: 8.6, h: 4.5, fontSize: 16, color: "222222" },
          );
        }
        const file = await writeOut(
          safeName(spec.title),
          "pptx",
          (await (pptx as unknown as { write: (m: string) => Promise<Buffer> }).write(
            "nodebuffer",
          )) as Buffer,
        );
        ctx.log({
          level: "success",
          source: "office",
          message: `Presentation saved: ${path.basename(file)}`,
        });
        return ok("Presentation created successfully.", {
          fileName: path.basename(file),
          location: file,
          type: "powerpoint",
        });
      } catch (err) {
        return fail(`PowerPoint generation failed: ${(err as Error).message}`, {
          errorCode: "PPTX_ERROR",
        });
      }
    },
  });

  registerTool({
    name: "office.excel",
    category: "office",
    description: "Create an Excel spreadsheet (.xlsx) from a topic or explicit columns/rows.",
    risk: "low",
    requiresConfirmation: false,
    parameters: [
      {
        name: "topic",
        type: "string",
        description: "What the spreadsheet should contain",
        required: true,
      },
      {
        name: "rows",
        type: "number",
        description: "Approximate number of data rows",
        required: false,
      },
    ],
    examples: ["Create an Excel study schedule for my exams."],
    async execute(params, ctx: ToolContext): Promise<ToolResult> {
      const topic = String(params.topic ?? "Sheet");
      const rowCount = Math.min(Math.max(Number(params.rows ?? 10), 3), 50);
      let table: { title: string; headers: string[]; rows: string[][] };
      try {
        ctx.log({ level: "info", source: "office", message: `Planning spreadsheet: ${topic}` });
        table = await runLordJson({
          system: "You are a spreadsheet designer. Produce clean tabular data.",
          prompt: `Design an Excel sheet about: ${topic}. Aim for ~${rowCount} data rows. Return JSON: { title:string, headers:string[], rows: string[][] (each inner array length must equal headers length) }.`,
          schemaHint: '{ "title": string, "headers": string[], "rows": string[][] }',
          mode: "coding",
        });
        if (!table?.headers?.length || !Array.isArray(table.rows)) throw new Error("bad shape");
      } catch {
        table = {
          title: topic,
          headers: ["Item", "Detail", "Status"],
          rows: Array.from({ length: rowCount }, (_, i) => [
            `Item ${i + 1}`,
            "Auto-generated",
            "Pending",
          ]),
        };
      }

      try {
        const wb = new ExcelJS.Workbook();
        const ws = wb.addWorksheet(table.title.slice(0, 28) || "Sheet");
        ws.addRow(table.headers);
        ws.getRow(1).font = { bold: true };
        ws.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1F2A44" } };
        ws.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
        for (const r of table.rows) ws.addRow(r);
        ws.columns.forEach((c) => (c.width = 22));
        const buffer = await wb.xlsx.writeBuffer();
        const file = await writeOut(safeName(table.title), "xlsx", Buffer.from(buffer));
        ctx.log({
          level: "success",
          source: "office",
          message: `Spreadsheet saved: ${path.basename(file)}`,
        });
        return ok("Spreadsheet created successfully.", {
          fileName: path.basename(file),
          location: file,
          type: "excel",
        });
      } catch (err) {
        return fail(`Excel generation failed: ${(err as Error).message}`, {
          errorCode: "XLSX_ERROR",
        });
      }
    },
  });

  registerTool({
    name: "office.document",
    category: "office",
    description: "Generate a structured Word document (.docx) from a topic or outline.",
    risk: "low",
    requiresConfirmation: false,
    parameters: [
      { name: "topic", type: "string", description: "Subject of the document", required: true },
      {
        name: "sections",
        type: "number",
        description: "Approximate number of sections",
        required: false,
      },
    ],
    examples: ["Write a structured report about renewable energy."],
    async execute(params, ctx: ToolContext): Promise<ToolResult> {
      const topic = String(params.topic ?? "Document");
      const sectionCount = Math.min(Math.max(Number(params.sections ?? 5), 2), 15);
      let outline: { title: string; sections: { heading: string; body: string }[] };
      try {
        ctx.log({ level: "info", source: "office", message: `Planning document: ${topic}` });
        outline = await runLordJson({
          system: "You are a technical writer. Produce a structured document outline.",
          prompt: `Write a document about: ${topic}. Use ~${sectionCount} sections. Return JSON: { title:string, sections:[{heading:string, body:string}] }.`,
          schemaHint: '{ "title": string, "sections": [{"heading": string, "body": string}] }',
          mode: "creative",
        });
        if (!outline?.sections?.length) throw new Error("empty");
      } catch {
        outline = {
          title: topic,
          sections: Array.from({ length: sectionCount }, (_, i) => ({
            heading: `Section ${i + 1}`,
            body: "Auto-generated content for this section.",
          })),
        };
      }

      try {
        const children: Paragraph[] = [
          new Paragraph({ text: outline.title, heading: HeadingLevel.TITLE }),
        ];
        for (const s of outline.sections) {
          children.push(new Paragraph({ text: s.heading, heading: HeadingLevel.HEADING_1 }));
          for (const para of s.body.split(/\n{1,}/).filter(Boolean)) {
            children.push(new Paragraph({ children: [new TextRun(para)] }));
          }
        }
        const doc = new Document({ sections: [{ children }] });
        const buffer = await Packer.toBuffer(doc);
        const file = await writeOut(safeName(outline.title), "docx", buffer);
        ctx.log({
          level: "success",
          source: "office",
          message: `Document saved: ${path.basename(file)}`,
        });
        return ok("Document created successfully.", {
          fileName: path.basename(file),
          location: file,
          type: "document",
        });
      } catch (err) {
        return fail(`Document generation failed: ${(err as Error).message}`, {
          errorCode: "DOCX_ERROR",
        });
      }
    },
  });
}
