/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ApiTitleRouteImport } from './routes/api/title'
import { Route as ApiSharesRouteImport } from './routes/api/shares'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOpenrouterTestRouteImport } from './routes/api/openrouter-test'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProductivityRouteImport } from './routes/_authenticated/productivity'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBoardsRouteImport } from './routes/_authenticated/boards'
import { Route as AuthenticatedCommandCenterRouteRouteImport } from './routes/_authenticated/command-center/route'
import { Route as ApiStudyPlansIndexRouteImport } from './routes/api/study-plans/index'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiKnowledgeIndexRouteImport } from './routes/api/knowledge/index'
import { Route as ApiDashboardsIndexRouteImport } from './routes/api/dashboards/index'
import { Route as ApiCanvasIndexRouteImport } from './routes/api/canvas/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedObservabilityIndexRouteImport } from './routes/_authenticated/observability/index'
import { Route as AuthenticatedKnowledge2IndexRouteImport } from './routes/_authenticated/knowledge2/index'
import { Route as AuthenticatedDashboardsIndexRouteImport } from './routes/_authenticated/dashboards/index'
import { Route as AuthenticatedCommandCenterIndexRouteImport } from './routes/_authenticated/command-center/index'
import { Route as AuthenticatedCanvasIndexRouteImport } from './routes/_authenticated/canvas/index'
import { Route as ApiStudyPlansIdRouteImport } from './routes/api/study-plans/$id'
import { Route as ApiSharesTokenRouteImport } from './routes/api/shares/$token'
import { Route as ApiSharedTokenRouteImport } from './routes/api/shared/$token'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiObservabilityHealthRouteImport } from './routes/api/observability/health'
import { Route as ApiLordToolRouteImport } from './routes/api/lord/tool'
import { Route as ApiLordStatusRouteImport } from './routes/api/lord/status'
import { Route as ApiLordFilesRouteImport } from './routes/api/lord/files'
import { Route as ApiLordFileRouteImport } from './routes/api/lord/file'
import { Route as ApiLordAutomationRouteImport } from './routes/api/lord/automation'
import { Route as ApiLordActivityRouteImport } from './routes/api/lord/activity'
import { Route as ApiLearningWhiteboardRouteImport } from './routes/api/learning/whiteboard'
import { Route as ApiLearningVoiceRouteImport } from './routes/api/learning/voice'
import { Route as ApiLearningSessionRouteImport } from './routes/api/learning/session'
import { Route as ApiLearningRevisionRouteImport } from './routes/api/learning/revision'
import { Route as ApiLearningOcrRouteImport } from './routes/api/learning/ocr'
import { Route as ApiLearningNotesRouteImport } from './routes/api/learning/notes'
import { Route as ApiLearningMemoryRouteImport } from './routes/api/learning/memory'
import { Route as ApiLearningGoalsRouteImport } from './routes/api/learning/goals'
import { Route as ApiLearningFlashcardsRouteImport } from './routes/api/learning/flashcards'
import { Route as ApiLearningFeaturesRouteImport } from './routes/api/learning/features'
import { Route as ApiLearningExamsRouteImport } from './routes/api/learning/exams'
import { Route as ApiLearningAnalyticsRouteImport } from './routes/api/learning/analytics'
import { Route as ApiKnowledge2RelationsRouteImport } from './routes/api/knowledge2/relations'
import { Route as ApiKnowledge2EntitiesRouteImport } from './routes/api/knowledge2/entities'
import { Route as ApiKnowledgeUploadRouteImport } from './routes/api/knowledge/upload'
import { Route as ApiKnowledgeIdRouteImport } from './routes/api/knowledge/$id'
import { Route as ApiImagesRegenerateRouteImport } from './routes/api/images/regenerate'
import { Route as ApiImagesModelsRouteImport } from './routes/api/images/models'
import { Route as ApiImagesIdRouteImport } from './routes/api/images/$id'
import { Route as ApiImageHealthRouteImport } from './routes/api/image/health'
import { Route as ApiCommandPaletteSearchRouteImport } from './routes/api/command-palette/search'
import { Route as ApiCanvasVersionsRouteImport } from './routes/api/canvas/versions'
import { Route as ApiCanvasStreamRouteImport } from './routes/api/canvas/stream'
import { Route as ApiBrainContextRouteImport } from './routes/api/brain/context'
import { Route as ApiAdminGatewayRouteImport } from './routes/api/admin/gateway'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedCommandCenterVisionRouteImport } from './routes/_authenticated/command-center/vision'
import { Route as AuthenticatedCommandCenterSmartHomeRouteImport } from './routes/_authenticated/command-center/smart-home'
import { Route as AuthenticatedCommandCenterSettingsRouteImport } from './routes/_authenticated/command-center/settings'
import { Route as AuthenticatedCommandCenterPcRouteImport } from './routes/_authenticated/command-center/pc'
import { Route as AuthenticatedCommandCenterOfficeRouteImport } from './routes/_authenticated/command-center/office'
import { Route as AuthenticatedCommandCenterMobileRouteImport } from './routes/_authenticated/command-center/mobile'
import { Route as AuthenticatedCommandCenterFilesRouteImport } from './routes/_authenticated/command-center/files'
import { Route as AuthenticatedCommandCenterBrowserRouteImport } from './routes/_authenticated/command-center/browser'
import { Route as AuthenticatedCommandCenterAutomationsRouteImport } from './routes/_authenticated/command-center/automations'
import { Route as AuthenticatedCanvasIdRouteImport } from './routes/_authenticated/canvas/$id'
import { Route as ApiLordVisionWebcamRouteImport } from './routes/api/lord/vision/webcam'
import { Route as ApiLordVisionScreenRouteImport } from './routes/api/lord/vision/screen'
import { Route as ApiLordOfficePowerpointRouteImport } from './routes/api/lord/office/powerpoint'
import { Route as ApiLordOfficeExcelRouteImport } from './routes/api/lord/office/excel'
import { Route as ApiLordMobileStatusRouteImport } from './routes/api/lord/mobile/status'
import { Route as ApiLordMobilePairRouteImport } from './routes/api/lord/mobile/pair'
import { Route as ApiLordIotDevicesRouteImport } from './routes/api/lord/iot/devices'
import { Route as ApiLordBrowserActionRouteImport } from './routes/api/lord/browser/action'
import { Route as ApiLordAgentStopRouteImport } from './routes/api/lord/agent/stop'
import { Route as ApiLordAgentExecuteRouteImport } from './routes/api/lord/agent/execute'
import { Route as ApiLearningSourcesIngestRouteImport } from './routes/api/learning/sources/ingest'
import { Route as ApiStudyPlansIdTasksIndexRouteImport } from './routes/api/study-plans/$id/tasks/index'
import { Route as ApiResearchIdSourcesIndexRouteImport } from './routes/api/research/$id/sources/index'
import { Route as ApiStudyPlansIdTasksTaskIdRouteImport } from './routes/api/study-plans/$id/tasks/$taskId'
import { Route as ApiStudyPlansIdAiSuggestRouteImport } from './routes/api/study-plans/$id/ai/suggest'
import { Route as ApiStudyPlansIdAiOptimizeRouteImport } from './routes/api/study-plans/$id/ai/optimize'
import { Route as ApiStudyPlansIdAiGenerateRouteImport } from './routes/api/study-plans/$id/ai/generate'
import { Route as ApiLordIotDeviceActionRouteImport } from './routes/api/lord/iot/device/action'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTitleRoute = ApiTitleRouteImport.update({
  id: '/api/title',
  path: '/api/title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterTestRoute = ApiOpenrouterTestRouteImport.update({
  id: '/api/openrouter-test',
  path: '/api/openrouter-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductivityRoute =
  AuthenticatedProductivityRouteImport.update({
    id: '/productivity',
    path: '/productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsRoute = AuthenticatedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRouteRoute =
  AuthenticatedCommandCenterRouteRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiStudyPlansIndexRoute = ApiStudyPlansIndexRouteImport.update({
  id: '/api/study-plans/',
  path: '/api/study-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeIndexRoute = ApiKnowledgeIndexRouteImport.update({
  id: '/api/knowledge/',
  path: '/api/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardsIndexRoute = ApiDashboardsIndexRouteImport.update({
  id: '/api/dashboards/',
  path: '/api/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasIndexRoute = ApiCanvasIndexRouteImport.update({
  id: '/api/canvas/',
  path: '/api/canvas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObservabilityIndexRoute =
  AuthenticatedObservabilityIndexRouteImport.update({
    id: '/observability/',
    path: '/observability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledge2IndexRoute =
  AuthenticatedKnowledge2IndexRouteImport.update({
    id: '/knowledge2/',
    path: '/knowledge2/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsIndexRoute =
  AuthenticatedDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandCenterIndexRoute =
  AuthenticatedCommandCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCanvasIndexRoute =
  AuthenticatedCanvasIndexRouteImport.update({
    id: '/canvas/',
    path: '/canvas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiStudyPlansIdRoute = ApiStudyPlansIdRouteImport.update({
  id: '/api/study-plans/$id',
  path: '/api/study-plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesTokenRoute = ApiSharesTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ApiSharesRoute,
} as any)
const ApiSharedTokenRoute = ApiSharedTokenRouteImport.update({
  id: '/api/shared/$token',
  path: '/api/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityHealthRoute = ApiObservabilityHealthRouteImport.update({
  id: '/api/observability/health',
  path: '/api/observability/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordToolRoute = ApiLordToolRouteImport.update({
  id: '/api/lord/tool',
  path: '/api/lord/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordStatusRoute = ApiLordStatusRouteImport.update({
  id: '/api/lord/status',
  path: '/api/lord/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordFilesRoute = ApiLordFilesRouteImport.update({
  id: '/api/lord/files',
  path: '/api/lord/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordFileRoute = ApiLordFileRouteImport.update({
  id: '/api/lord/file',
  path: '/api/lord/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordAutomationRoute = ApiLordAutomationRouteImport.update({
  id: '/api/lord/automation',
  path: '/api/lord/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordActivityRoute = ApiLordActivityRouteImport.update({
  id: '/api/lord/activity',
  path: '/api/lord/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningWhiteboardRoute = ApiLearningWhiteboardRouteImport.update({
  id: '/api/learning/whiteboard',
  path: '/api/learning/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningVoiceRoute = ApiLearningVoiceRouteImport.update({
  id: '/api/learning/voice',
  path: '/api/learning/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningSessionRoute = ApiLearningSessionRouteImport.update({
  id: '/api/learning/session',
  path: '/api/learning/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningRevisionRoute = ApiLearningRevisionRouteImport.update({
  id: '/api/learning/revision',
  path: '/api/learning/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningOcrRoute = ApiLearningOcrRouteImport.update({
  id: '/api/learning/ocr',
  path: '/api/learning/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningNotesRoute = ApiLearningNotesRouteImport.update({
  id: '/api/learning/notes',
  path: '/api/learning/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningMemoryRoute = ApiLearningMemoryRouteImport.update({
  id: '/api/learning/memory',
  path: '/api/learning/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningGoalsRoute = ApiLearningGoalsRouteImport.update({
  id: '/api/learning/goals',
  path: '/api/learning/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningFlashcardsRoute = ApiLearningFlashcardsRouteImport.update({
  id: '/api/learning/flashcards',
  path: '/api/learning/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningFeaturesRoute = ApiLearningFeaturesRouteImport.update({
  id: '/api/learning/features',
  path: '/api/learning/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningExamsRoute = ApiLearningExamsRouteImport.update({
  id: '/api/learning/exams',
  path: '/api/learning/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningAnalyticsRoute = ApiLearningAnalyticsRouteImport.update({
  id: '/api/learning/analytics',
  path: '/api/learning/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledge2RelationsRoute = ApiKnowledge2RelationsRouteImport.update({
  id: '/api/knowledge2/relations',
  path: '/api/knowledge2/relations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledge2EntitiesRoute = ApiKnowledge2EntitiesRouteImport.update({
  id: '/api/knowledge2/entities',
  path: '/api/knowledge2/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeUploadRoute = ApiKnowledgeUploadRouteImport.update({
  id: '/api/knowledge/upload',
  path: '/api/knowledge/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeIdRoute = ApiKnowledgeIdRouteImport.update({
  id: '/api/knowledge/$id',
  path: '/api/knowledge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRegenerateRoute = ApiImagesRegenerateRouteImport.update({
  id: '/regenerate',
  path: '/regenerate',
  getParentRoute: () => ApiImagesRoute,
} as any)
const ApiImagesModelsRoute = ApiImagesModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiImagesRoute,
} as any)
const ApiImagesIdRoute = ApiImagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiImagesRoute,
} as any)
const ApiImageHealthRoute = ApiImageHealthRouteImport.update({
  id: '/api/image/health',
  path: '/api/image/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommandPaletteSearchRoute = ApiCommandPaletteSearchRouteImport.update({
  id: '/api/command-palette/search',
  path: '/api/command-palette/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasVersionsRoute = ApiCanvasVersionsRouteImport.update({
  id: '/api/canvas/versions',
  path: '/api/canvas/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasStreamRoute = ApiCanvasStreamRouteImport.update({
  id: '/api/canvas/stream',
  path: '/api/canvas/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainContextRoute = ApiBrainContextRouteImport.update({
  id: '/api/brain/context',
  path: '/api/brain/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGatewayRoute = ApiAdminGatewayRouteImport.update({
  id: '/api/admin/gateway',
  path: '/api/admin/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterVisionRoute =
  AuthenticatedCommandCenterVisionRouteImport.update({
    id: '/vision',
    path: '/vision',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterSmartHomeRoute =
  AuthenticatedCommandCenterSmartHomeRouteImport.update({
    id: '/smart-home',
    path: '/smart-home',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterSettingsRoute =
  AuthenticatedCommandCenterSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterPcRoute =
  AuthenticatedCommandCenterPcRouteImport.update({
    id: '/pc',
    path: '/pc',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterOfficeRoute =
  AuthenticatedCommandCenterOfficeRouteImport.update({
    id: '/office',
    path: '/office',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterMobileRoute =
  AuthenticatedCommandCenterMobileRouteImport.update({
    id: '/mobile',
    path: '/mobile',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterFilesRoute =
  AuthenticatedCommandCenterFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterBrowserRoute =
  AuthenticatedCommandCenterBrowserRouteImport.update({
    id: '/browser',
    path: '/browser',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCommandCenterAutomationsRoute =
  AuthenticatedCommandCenterAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedCommandCenterRouteRoute,
  } as any)
const AuthenticatedCanvasIdRoute = AuthenticatedCanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLordVisionWebcamRoute = ApiLordVisionWebcamRouteImport.update({
  id: '/api/lord/vision/webcam',
  path: '/api/lord/vision/webcam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordVisionScreenRoute = ApiLordVisionScreenRouteImport.update({
  id: '/api/lord/vision/screen',
  path: '/api/lord/vision/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordOfficePowerpointRoute = ApiLordOfficePowerpointRouteImport.update({
  id: '/api/lord/office/powerpoint',
  path: '/api/lord/office/powerpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordOfficeExcelRoute = ApiLordOfficeExcelRouteImport.update({
  id: '/api/lord/office/excel',
  path: '/api/lord/office/excel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordMobileStatusRoute = ApiLordMobileStatusRouteImport.update({
  id: '/api/lord/mobile/status',
  path: '/api/lord/mobile/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordMobilePairRoute = ApiLordMobilePairRouteImport.update({
  id: '/api/lord/mobile/pair',
  path: '/api/lord/mobile/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordIotDevicesRoute = ApiLordIotDevicesRouteImport.update({
  id: '/api/lord/iot/devices',
  path: '/api/lord/iot/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordBrowserActionRoute = ApiLordBrowserActionRouteImport.update({
  id: '/api/lord/browser/action',
  path: '/api/lord/browser/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordAgentStopRoute = ApiLordAgentStopRouteImport.update({
  id: '/api/lord/agent/stop',
  path: '/api/lord/agent/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLordAgentExecuteRoute = ApiLordAgentExecuteRouteImport.update({
  id: '/api/lord/agent/execute',
  path: '/api/lord/agent/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningSourcesIngestRoute =
  ApiLearningSourcesIngestRouteImport.update({
    id: '/api/learning/sources/ingest',
    path: '/api/learning/sources/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStudyPlansIdTasksIndexRoute =
  ApiStudyPlansIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => ApiStudyPlansIdRoute,
  } as any)
const ApiResearchIdSourcesIndexRoute =
  ApiResearchIdSourcesIndexRouteImport.update({
    id: '/api/research/$id/sources/',
    path: '/api/research/$id/sources/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStudyPlansIdTasksTaskIdRoute =
  ApiStudyPlansIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ApiStudyPlansIdRoute,
  } as any)
const ApiStudyPlansIdAiSuggestRoute =
  ApiStudyPlansIdAiSuggestRouteImport.update({
    id: '/ai/suggest',
    path: '/ai/suggest',
    getParentRoute: () => ApiStudyPlansIdRoute,
  } as any)
const ApiStudyPlansIdAiOptimizeRoute =
  ApiStudyPlansIdAiOptimizeRouteImport.update({
    id: '/ai/optimize',
    path: '/ai/optimize',
    getParentRoute: () => ApiStudyPlansIdRoute,
  } as any)
const ApiStudyPlansIdAiGenerateRoute =
  ApiStudyPlansIdAiGenerateRouteImport.update({
    id: '/ai/generate',
    path: '/ai/generate',
    getParentRoute: () => ApiStudyPlansIdRoute,
  } as any)
const ApiLordIotDeviceActionRoute = ApiLordIotDeviceActionRouteImport.update({
  id: '/api/lord/iot/device/action',
  path: '/api/lord/iot/device/action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/command-center': typeof AuthenticatedCommandCenterRouteRouteWithChildren
  '/boards': typeof AuthenticatedBoardsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/images': typeof AuthenticatedImagesRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/title': typeof ApiTitleRoute
  '/share/$token': typeof ShareTokenRoute
  '/canvas/$id': typeof AuthenticatedCanvasIdRoute
  '/command-center/automations': typeof AuthenticatedCommandCenterAutomationsRoute
  '/command-center/browser': typeof AuthenticatedCommandCenterBrowserRoute
  '/command-center/files': typeof AuthenticatedCommandCenterFilesRoute
  '/command-center/mobile': typeof AuthenticatedCommandCenterMobileRoute
  '/command-center/office': typeof AuthenticatedCommandCenterOfficeRoute
  '/command-center/pc': typeof AuthenticatedCommandCenterPcRoute
  '/command-center/settings': typeof AuthenticatedCommandCenterSettingsRoute
  '/command-center/smart-home': typeof AuthenticatedCommandCenterSmartHomeRoute
  '/command-center/vision': typeof AuthenticatedCommandCenterVisionRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/admin/gateway': typeof ApiAdminGatewayRoute
  '/api/brain/context': typeof ApiBrainContextRoute
  '/api/canvas/stream': typeof ApiCanvasStreamRoute
  '/api/canvas/versions': typeof ApiCanvasVersionsRoute
  '/api/command-palette/search': typeof ApiCommandPaletteSearchRoute
  '/api/image/health': typeof ApiImageHealthRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/api/images/models': typeof ApiImagesModelsRoute
  '/api/images/regenerate': typeof ApiImagesRegenerateRoute
  '/api/knowledge/$id': typeof ApiKnowledgeIdRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge2/entities': typeof ApiKnowledge2EntitiesRoute
  '/api/knowledge2/relations': typeof ApiKnowledge2RelationsRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/exams': typeof ApiLearningExamsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/lord/activity': typeof ApiLordActivityRoute
  '/api/lord/automation': typeof ApiLordAutomationRoute
  '/api/lord/file': typeof ApiLordFileRoute
  '/api/lord/files': typeof ApiLordFilesRoute
  '/api/lord/status': typeof ApiLordStatusRoute
  '/api/lord/tool': typeof ApiLordToolRoute
  '/api/observability/health': typeof ApiObservabilityHealthRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/study-plans/$id': typeof ApiStudyPlansIdRouteWithChildren
  '/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/command-center/': typeof AuthenticatedCommandCenterIndexRoute
  '/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/knowledge2/': typeof AuthenticatedKnowledge2IndexRoute
  '/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/canvas/': typeof ApiCanvasIndexRoute
  '/api/dashboards/': typeof ApiDashboardsIndexRoute
  '/api/knowledge/': typeof ApiKnowledgeIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/study-plans/': typeof ApiStudyPlansIndexRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
  '/api/lord/agent/execute': typeof ApiLordAgentExecuteRoute
  '/api/lord/agent/stop': typeof ApiLordAgentStopRoute
  '/api/lord/browser/action': typeof ApiLordBrowserActionRoute
  '/api/lord/iot/devices': typeof ApiLordIotDevicesRoute
  '/api/lord/mobile/pair': typeof ApiLordMobilePairRoute
  '/api/lord/mobile/status': typeof ApiLordMobileStatusRoute
  '/api/lord/office/excel': typeof ApiLordOfficeExcelRoute
  '/api/lord/office/powerpoint': typeof ApiLordOfficePowerpointRoute
  '/api/lord/vision/screen': typeof ApiLordVisionScreenRoute
  '/api/lord/vision/webcam': typeof ApiLordVisionWebcamRoute
  '/api/lord/iot/device/action': typeof ApiLordIotDeviceActionRoute
  '/api/study-plans/$id/ai/generate': typeof ApiStudyPlansIdAiGenerateRoute
  '/api/study-plans/$id/ai/optimize': typeof ApiStudyPlansIdAiOptimizeRoute
  '/api/study-plans/$id/ai/suggest': typeof ApiStudyPlansIdAiSuggestRoute
  '/api/study-plans/$id/tasks/$taskId': typeof ApiStudyPlansIdTasksTaskIdRoute
  '/api/research/$id/sources/': typeof ApiResearchIdSourcesIndexRoute
  '/api/study-plans/$id/tasks/': typeof ApiStudyPlansIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/boards': typeof AuthenticatedBoardsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/images': typeof AuthenticatedImagesRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/title': typeof ApiTitleRoute
  '/share/$token': typeof ShareTokenRoute
  '/canvas/$id': typeof AuthenticatedCanvasIdRoute
  '/command-center/automations': typeof AuthenticatedCommandCenterAutomationsRoute
  '/command-center/browser': typeof AuthenticatedCommandCenterBrowserRoute
  '/command-center/files': typeof AuthenticatedCommandCenterFilesRoute
  '/command-center/mobile': typeof AuthenticatedCommandCenterMobileRoute
  '/command-center/office': typeof AuthenticatedCommandCenterOfficeRoute
  '/command-center/pc': typeof AuthenticatedCommandCenterPcRoute
  '/command-center/settings': typeof AuthenticatedCommandCenterSettingsRoute
  '/command-center/smart-home': typeof AuthenticatedCommandCenterSmartHomeRoute
  '/command-center/vision': typeof AuthenticatedCommandCenterVisionRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/admin/gateway': typeof ApiAdminGatewayRoute
  '/api/brain/context': typeof ApiBrainContextRoute
  '/api/canvas/stream': typeof ApiCanvasStreamRoute
  '/api/canvas/versions': typeof ApiCanvasVersionsRoute
  '/api/command-palette/search': typeof ApiCommandPaletteSearchRoute
  '/api/image/health': typeof ApiImageHealthRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/api/images/models': typeof ApiImagesModelsRoute
  '/api/images/regenerate': typeof ApiImagesRegenerateRoute
  '/api/knowledge/$id': typeof ApiKnowledgeIdRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge2/entities': typeof ApiKnowledge2EntitiesRoute
  '/api/knowledge2/relations': typeof ApiKnowledge2RelationsRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/exams': typeof ApiLearningExamsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/lord/activity': typeof ApiLordActivityRoute
  '/api/lord/automation': typeof ApiLordAutomationRoute
  '/api/lord/file': typeof ApiLordFileRoute
  '/api/lord/files': typeof ApiLordFilesRoute
  '/api/lord/status': typeof ApiLordStatusRoute
  '/api/lord/tool': typeof ApiLordToolRoute
  '/api/observability/health': typeof ApiObservabilityHealthRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/study-plans/$id': typeof ApiStudyPlansIdRouteWithChildren
  '/canvas': typeof AuthenticatedCanvasIndexRoute
  '/command-center': typeof AuthenticatedCommandCenterIndexRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexRoute
  '/knowledge2': typeof AuthenticatedKnowledge2IndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/canvas': typeof ApiCanvasIndexRoute
  '/api/dashboards': typeof ApiDashboardsIndexRoute
  '/api/knowledge': typeof ApiKnowledgeIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/study-plans': typeof ApiStudyPlansIndexRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
  '/api/lord/agent/execute': typeof ApiLordAgentExecuteRoute
  '/api/lord/agent/stop': typeof ApiLordAgentStopRoute
  '/api/lord/browser/action': typeof ApiLordBrowserActionRoute
  '/api/lord/iot/devices': typeof ApiLordIotDevicesRoute
  '/api/lord/mobile/pair': typeof ApiLordMobilePairRoute
  '/api/lord/mobile/status': typeof ApiLordMobileStatusRoute
  '/api/lord/office/excel': typeof ApiLordOfficeExcelRoute
  '/api/lord/office/powerpoint': typeof ApiLordOfficePowerpointRoute
  '/api/lord/vision/screen': typeof ApiLordVisionScreenRoute
  '/api/lord/vision/webcam': typeof ApiLordVisionWebcamRoute
  '/api/lord/iot/device/action': typeof ApiLordIotDeviceActionRoute
  '/api/study-plans/$id/ai/generate': typeof ApiStudyPlansIdAiGenerateRoute
  '/api/study-plans/$id/ai/optimize': typeof ApiStudyPlansIdAiOptimizeRoute
  '/api/study-plans/$id/ai/suggest': typeof ApiStudyPlansIdAiSuggestRoute
  '/api/study-plans/$id/tasks/$taskId': typeof ApiStudyPlansIdTasksTaskIdRoute
  '/api/research/$id/sources': typeof ApiResearchIdSourcesIndexRoute
  '/api/study-plans/$id/tasks': typeof ApiStudyPlansIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRouteRouteWithChildren
  '/_authenticated/boards': typeof AuthenticatedBoardsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/productivity': typeof AuthenticatedProductivityRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/title': typeof ApiTitleRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/canvas/$id': typeof AuthenticatedCanvasIdRoute
  '/_authenticated/command-center/automations': typeof AuthenticatedCommandCenterAutomationsRoute
  '/_authenticated/command-center/browser': typeof AuthenticatedCommandCenterBrowserRoute
  '/_authenticated/command-center/files': typeof AuthenticatedCommandCenterFilesRoute
  '/_authenticated/command-center/mobile': typeof AuthenticatedCommandCenterMobileRoute
  '/_authenticated/command-center/office': typeof AuthenticatedCommandCenterOfficeRoute
  '/_authenticated/command-center/pc': typeof AuthenticatedCommandCenterPcRoute
  '/_authenticated/command-center/settings': typeof AuthenticatedCommandCenterSettingsRoute
  '/_authenticated/command-center/smart-home': typeof AuthenticatedCommandCenterSmartHomeRoute
  '/_authenticated/command-center/vision': typeof AuthenticatedCommandCenterVisionRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/admin/gateway': typeof ApiAdminGatewayRoute
  '/api/brain/context': typeof ApiBrainContextRoute
  '/api/canvas/stream': typeof ApiCanvasStreamRoute
  '/api/canvas/versions': typeof ApiCanvasVersionsRoute
  '/api/command-palette/search': typeof ApiCommandPaletteSearchRoute
  '/api/image/health': typeof ApiImageHealthRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/api/images/models': typeof ApiImagesModelsRoute
  '/api/images/regenerate': typeof ApiImagesRegenerateRoute
  '/api/knowledge/$id': typeof ApiKnowledgeIdRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge2/entities': typeof ApiKnowledge2EntitiesRoute
  '/api/knowledge2/relations': typeof ApiKnowledge2RelationsRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/exams': typeof ApiLearningExamsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/lord/activity': typeof ApiLordActivityRoute
  '/api/lord/automation': typeof ApiLordAutomationRoute
  '/api/lord/file': typeof ApiLordFileRoute
  '/api/lord/files': typeof ApiLordFilesRoute
  '/api/lord/status': typeof ApiLordStatusRoute
  '/api/lord/tool': typeof ApiLordToolRoute
  '/api/observability/health': typeof ApiObservabilityHealthRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/study-plans/$id': typeof ApiStudyPlansIdRouteWithChildren
  '/_authenticated/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/_authenticated/command-center/': typeof AuthenticatedCommandCenterIndexRoute
  '/_authenticated/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/_authenticated/knowledge2/': typeof AuthenticatedKnowledge2IndexRoute
  '/_authenticated/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/canvas/': typeof ApiCanvasIndexRoute
  '/api/dashboards/': typeof ApiDashboardsIndexRoute
  '/api/knowledge/': typeof ApiKnowledgeIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/study-plans/': typeof ApiStudyPlansIndexRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
  '/api/lord/agent/execute': typeof ApiLordAgentExecuteRoute
  '/api/lord/agent/stop': typeof ApiLordAgentStopRoute
  '/api/lord/browser/action': typeof ApiLordBrowserActionRoute
  '/api/lord/iot/devices': typeof ApiLordIotDevicesRoute
  '/api/lord/mobile/pair': typeof ApiLordMobilePairRoute
  '/api/lord/mobile/status': typeof ApiLordMobileStatusRoute
  '/api/lord/office/excel': typeof ApiLordOfficeExcelRoute
  '/api/lord/office/powerpoint': typeof ApiLordOfficePowerpointRoute
  '/api/lord/vision/screen': typeof ApiLordVisionScreenRoute
  '/api/lord/vision/webcam': typeof ApiLordVisionWebcamRoute
  '/api/lord/iot/device/action': typeof ApiLordIotDeviceActionRoute
  '/api/study-plans/$id/ai/generate': typeof ApiStudyPlansIdAiGenerateRoute
  '/api/study-plans/$id/ai/optimize': typeof ApiStudyPlansIdAiOptimizeRoute
  '/api/study-plans/$id/ai/suggest': typeof ApiStudyPlansIdAiSuggestRoute
  '/api/study-plans/$id/tasks/$taskId': typeof ApiStudyPlansIdTasksTaskIdRoute
  '/api/research/$id/sources/': typeof ApiResearchIdSourcesIndexRoute
  '/api/study-plans/$id/tasks/': typeof ApiStudyPlansIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/command-center'
    | '/boards'
    | '/calendar'
    | '/chat'
    | '/documents'
    | '/feed'
    | '/images'
    | '/learn'
    | '/memory'
    | '/plan'
    | '/practice'
    | '/productivity'
    | '/progress'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/study'
    | '/tasks'
    | '/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/images'
    | '/api/openrouter-test'
    | '/api/search'
    | '/api/shares'
    | '/api/title'
    | '/share/$token'
    | '/canvas/$id'
    | '/command-center/automations'
    | '/command-center/browser'
    | '/command-center/files'
    | '/command-center/mobile'
    | '/command-center/office'
    | '/command-center/pc'
    | '/command-center/settings'
    | '/command-center/smart-home'
    | '/command-center/vision'
    | '/projects/$id'
    | '/api/admin/gateway'
    | '/api/brain/context'
    | '/api/canvas/stream'
    | '/api/canvas/versions'
    | '/api/command-palette/search'
    | '/api/image/health'
    | '/api/images/$id'
    | '/api/images/models'
    | '/api/images/regenerate'
    | '/api/knowledge/$id'
    | '/api/knowledge/upload'
    | '/api/knowledge2/entities'
    | '/api/knowledge2/relations'
    | '/api/learning/analytics'
    | '/api/learning/exams'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/lord/activity'
    | '/api/lord/automation'
    | '/api/lord/file'
    | '/api/lord/files'
    | '/api/lord/status'
    | '/api/lord/tool'
    | '/api/observability/health'
    | '/api/projects/$id'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/study-plans/$id'
    | '/canvas/'
    | '/command-center/'
    | '/dashboards/'
    | '/knowledge2/'
    | '/observability/'
    | '/projects/'
    | '/api/canvas/'
    | '/api/dashboards/'
    | '/api/knowledge/'
    | '/api/projects/'
    | '/api/study-plans/'
    | '/api/learning/sources/ingest'
    | '/api/lord/agent/execute'
    | '/api/lord/agent/stop'
    | '/api/lord/browser/action'
    | '/api/lord/iot/devices'
    | '/api/lord/mobile/pair'
    | '/api/lord/mobile/status'
    | '/api/lord/office/excel'
    | '/api/lord/office/powerpoint'
    | '/api/lord/vision/screen'
    | '/api/lord/vision/webcam'
    | '/api/lord/iot/device/action'
    | '/api/study-plans/$id/ai/generate'
    | '/api/study-plans/$id/ai/optimize'
    | '/api/study-plans/$id/ai/suggest'
    | '/api/study-plans/$id/tasks/$taskId'
    | '/api/research/$id/sources/'
    | '/api/study-plans/$id/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/boards'
    | '/calendar'
    | '/chat'
    | '/documents'
    | '/feed'
    | '/images'
    | '/learn'
    | '/memory'
    | '/plan'
    | '/practice'
    | '/productivity'
    | '/progress'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/study'
    | '/tasks'
    | '/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/images'
    | '/api/openrouter-test'
    | '/api/search'
    | '/api/shares'
    | '/api/title'
    | '/share/$token'
    | '/canvas/$id'
    | '/command-center/automations'
    | '/command-center/browser'
    | '/command-center/files'
    | '/command-center/mobile'
    | '/command-center/office'
    | '/command-center/pc'
    | '/command-center/settings'
    | '/command-center/smart-home'
    | '/command-center/vision'
    | '/projects/$id'
    | '/api/admin/gateway'
    | '/api/brain/context'
    | '/api/canvas/stream'
    | '/api/canvas/versions'
    | '/api/command-palette/search'
    | '/api/image/health'
    | '/api/images/$id'
    | '/api/images/models'
    | '/api/images/regenerate'
    | '/api/knowledge/$id'
    | '/api/knowledge/upload'
    | '/api/knowledge2/entities'
    | '/api/knowledge2/relations'
    | '/api/learning/analytics'
    | '/api/learning/exams'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/lord/activity'
    | '/api/lord/automation'
    | '/api/lord/file'
    | '/api/lord/files'
    | '/api/lord/status'
    | '/api/lord/tool'
    | '/api/observability/health'
    | '/api/projects/$id'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/study-plans/$id'
    | '/canvas'
    | '/command-center'
    | '/dashboards'
    | '/knowledge2'
    | '/observability'
    | '/projects'
    | '/api/canvas'
    | '/api/dashboards'
    | '/api/knowledge'
    | '/api/projects'
    | '/api/study-plans'
    | '/api/learning/sources/ingest'
    | '/api/lord/agent/execute'
    | '/api/lord/agent/stop'
    | '/api/lord/browser/action'
    | '/api/lord/iot/devices'
    | '/api/lord/mobile/pair'
    | '/api/lord/mobile/status'
    | '/api/lord/office/excel'
    | '/api/lord/office/powerpoint'
    | '/api/lord/vision/screen'
    | '/api/lord/vision/webcam'
    | '/api/lord/iot/device/action'
    | '/api/study-plans/$id/ai/generate'
    | '/api/study-plans/$id/ai/optimize'
    | '/api/study-plans/$id/ai/suggest'
    | '/api/study-plans/$id/tasks/$taskId'
    | '/api/research/$id/sources'
    | '/api/study-plans/$id/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/command-center'
    | '/_authenticated/boards'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/documents'
    | '/_authenticated/feed'
    | '/_authenticated/images'
    | '/_authenticated/learn'
    | '/_authenticated/memory'
    | '/_authenticated/plan'
    | '/_authenticated/practice'
    | '/_authenticated/productivity'
    | '/_authenticated/progress'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/study'
    | '/_authenticated/tasks'
    | '/_authenticated/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/images'
    | '/api/openrouter-test'
    | '/api/search'
    | '/api/shares'
    | '/api/title'
    | '/share/$token'
    | '/_authenticated/canvas/$id'
    | '/_authenticated/command-center/automations'
    | '/_authenticated/command-center/browser'
    | '/_authenticated/command-center/files'
    | '/_authenticated/command-center/mobile'
    | '/_authenticated/command-center/office'
    | '/_authenticated/command-center/pc'
    | '/_authenticated/command-center/settings'
    | '/_authenticated/command-center/smart-home'
    | '/_authenticated/command-center/vision'
    | '/_authenticated/projects/$id'
    | '/api/admin/gateway'
    | '/api/brain/context'
    | '/api/canvas/stream'
    | '/api/canvas/versions'
    | '/api/command-palette/search'
    | '/api/image/health'
    | '/api/images/$id'
    | '/api/images/models'
    | '/api/images/regenerate'
    | '/api/knowledge/$id'
    | '/api/knowledge/upload'
    | '/api/knowledge2/entities'
    | '/api/knowledge2/relations'
    | '/api/learning/analytics'
    | '/api/learning/exams'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/lord/activity'
    | '/api/lord/automation'
    | '/api/lord/file'
    | '/api/lord/files'
    | '/api/lord/status'
    | '/api/lord/tool'
    | '/api/observability/health'
    | '/api/projects/$id'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/study-plans/$id'
    | '/_authenticated/canvas/'
    | '/_authenticated/command-center/'
    | '/_authenticated/dashboards/'
    | '/_authenticated/knowledge2/'
    | '/_authenticated/observability/'
    | '/_authenticated/projects/'
    | '/api/canvas/'
    | '/api/dashboards/'
    | '/api/knowledge/'
    | '/api/projects/'
    | '/api/study-plans/'
    | '/api/learning/sources/ingest'
    | '/api/lord/agent/execute'
    | '/api/lord/agent/stop'
    | '/api/lord/browser/action'
    | '/api/lord/iot/devices'
    | '/api/lord/mobile/pair'
    | '/api/lord/mobile/status'
    | '/api/lord/office/excel'
    | '/api/lord/office/powerpoint'
    | '/api/lord/vision/screen'
    | '/api/lord/vision/webcam'
    | '/api/lord/iot/device/action'
    | '/api/study-plans/$id/ai/generate'
    | '/api/study-plans/$id/ai/optimize'
    | '/api/study-plans/$id/ai/suggest'
    | '/api/study-plans/$id/tasks/$taskId'
    | '/api/research/$id/sources/'
    | '/api/study-plans/$id/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImagesRoute: typeof ApiImagesRouteWithChildren
  ApiOpenrouterTestRoute: typeof ApiOpenrouterTestRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSharesRoute: typeof ApiSharesRouteWithChildren
  ApiTitleRoute: typeof ApiTitleRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAdminGatewayRoute: typeof ApiAdminGatewayRoute
  ApiBrainContextRoute: typeof ApiBrainContextRoute
  ApiCanvasStreamRoute: typeof ApiCanvasStreamRoute
  ApiCanvasVersionsRoute: typeof ApiCanvasVersionsRoute
  ApiCommandPaletteSearchRoute: typeof ApiCommandPaletteSearchRoute
  ApiImageHealthRoute: typeof ApiImageHealthRoute
  ApiKnowledgeIdRoute: typeof ApiKnowledgeIdRoute
  ApiKnowledgeUploadRoute: typeof ApiKnowledgeUploadRoute
  ApiKnowledge2EntitiesRoute: typeof ApiKnowledge2EntitiesRoute
  ApiKnowledge2RelationsRoute: typeof ApiKnowledge2RelationsRoute
  ApiLearningAnalyticsRoute: typeof ApiLearningAnalyticsRoute
  ApiLearningExamsRoute: typeof ApiLearningExamsRoute
  ApiLearningFeaturesRoute: typeof ApiLearningFeaturesRoute
  ApiLearningFlashcardsRoute: typeof ApiLearningFlashcardsRoute
  ApiLearningGoalsRoute: typeof ApiLearningGoalsRoute
  ApiLearningMemoryRoute: typeof ApiLearningMemoryRoute
  ApiLearningNotesRoute: typeof ApiLearningNotesRoute
  ApiLearningOcrRoute: typeof ApiLearningOcrRoute
  ApiLearningRevisionRoute: typeof ApiLearningRevisionRoute
  ApiLearningSessionRoute: typeof ApiLearningSessionRoute
  ApiLearningVoiceRoute: typeof ApiLearningVoiceRoute
  ApiLearningWhiteboardRoute: typeof ApiLearningWhiteboardRoute
  ApiLordActivityRoute: typeof ApiLordActivityRoute
  ApiLordAutomationRoute: typeof ApiLordAutomationRoute
  ApiLordFileRoute: typeof ApiLordFileRoute
  ApiLordFilesRoute: typeof ApiLordFilesRoute
  ApiLordStatusRoute: typeof ApiLordStatusRoute
  ApiLordToolRoute: typeof ApiLordToolRoute
  ApiObservabilityHealthRoute: typeof ApiObservabilityHealthRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
  ApiSharedTokenRoute: typeof ApiSharedTokenRoute
  ApiStudyPlansIdRoute: typeof ApiStudyPlansIdRouteWithChildren
  ApiCanvasIndexRoute: typeof ApiCanvasIndexRoute
  ApiDashboardsIndexRoute: typeof ApiDashboardsIndexRoute
  ApiKnowledgeIndexRoute: typeof ApiKnowledgeIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiStudyPlansIndexRoute: typeof ApiStudyPlansIndexRoute
  ApiLearningSourcesIngestRoute: typeof ApiLearningSourcesIngestRoute
  ApiLordAgentExecuteRoute: typeof ApiLordAgentExecuteRoute
  ApiLordAgentStopRoute: typeof ApiLordAgentStopRoute
  ApiLordBrowserActionRoute: typeof ApiLordBrowserActionRoute
  ApiLordIotDevicesRoute: typeof ApiLordIotDevicesRoute
  ApiLordMobilePairRoute: typeof ApiLordMobilePairRoute
  ApiLordMobileStatusRoute: typeof ApiLordMobileStatusRoute
  ApiLordOfficeExcelRoute: typeof ApiLordOfficeExcelRoute
  ApiLordOfficePowerpointRoute: typeof ApiLordOfficePowerpointRoute
  ApiLordVisionScreenRoute: typeof ApiLordVisionScreenRoute
  ApiLordVisionWebcamRoute: typeof ApiLordVisionWebcamRoute
  ApiLordIotDeviceActionRoute: typeof ApiLordIotDeviceActionRoute
  ApiResearchIdSourcesIndexRoute: typeof ApiResearchIdSourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/title': {
      id: '/api/title'
      path: '/api/title'
      fullPath: '/api/title'
      preLoaderRoute: typeof ApiTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-test': {
      id: '/api/openrouter-test'
      path: '/api/openrouter-test'
      fullPath: '/api/openrouter-test'
      preLoaderRoute: typeof ApiOpenrouterTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity': {
      id: '/_authenticated/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof AuthenticatedProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards': {
      id: '/_authenticated/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AuthenticatedBoardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/study-plans/': {
      id: '/api/study-plans/'
      path: '/api/study-plans'
      fullPath: '/api/study-plans/'
      preLoaderRoute: typeof ApiStudyPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/': {
      id: '/api/knowledge/'
      path: '/api/knowledge'
      fullPath: '/api/knowledge/'
      preLoaderRoute: typeof ApiKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboards/': {
      id: '/api/dashboards/'
      path: '/api/dashboards'
      fullPath: '/api/dashboards/'
      preLoaderRoute: typeof ApiDashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/': {
      id: '/api/canvas/'
      path: '/api/canvas'
      fullPath: '/api/canvas/'
      preLoaderRoute: typeof ApiCanvasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observability/': {
      id: '/_authenticated/observability/'
      path: '/observability'
      fullPath: '/observability/'
      preLoaderRoute: typeof AuthenticatedObservabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge2/': {
      id: '/_authenticated/knowledge2/'
      path: '/knowledge2'
      fullPath: '/knowledge2/'
      preLoaderRoute: typeof AuthenticatedKnowledge2IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/': {
      id: '/_authenticated/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AuthenticatedDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center/': {
      id: '/_authenticated/command-center/'
      path: '/'
      fullPath: '/command-center/'
      preLoaderRoute: typeof AuthenticatedCommandCenterIndexRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/canvas/': {
      id: '/_authenticated/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof AuthenticatedCanvasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/study-plans/$id': {
      id: '/api/study-plans/$id'
      path: '/api/study-plans/$id'
      fullPath: '/api/study-plans/$id'
      preLoaderRoute: typeof ApiStudyPlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/$token': {
      id: '/api/shares/$token'
      path: '/$token'
      fullPath: '/api/shares/$token'
      preLoaderRoute: typeof ApiSharesTokenRouteImport
      parentRoute: typeof ApiSharesRoute
    }
    '/api/shared/$token': {
      id: '/api/shared/$token'
      path: '/api/shared/$token'
      fullPath: '/api/shared/$token'
      preLoaderRoute: typeof ApiSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/health': {
      id: '/api/observability/health'
      path: '/api/observability/health'
      fullPath: '/api/observability/health'
      preLoaderRoute: typeof ApiObservabilityHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/tool': {
      id: '/api/lord/tool'
      path: '/api/lord/tool'
      fullPath: '/api/lord/tool'
      preLoaderRoute: typeof ApiLordToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/status': {
      id: '/api/lord/status'
      path: '/api/lord/status'
      fullPath: '/api/lord/status'
      preLoaderRoute: typeof ApiLordStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/files': {
      id: '/api/lord/files'
      path: '/api/lord/files'
      fullPath: '/api/lord/files'
      preLoaderRoute: typeof ApiLordFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/file': {
      id: '/api/lord/file'
      path: '/api/lord/file'
      fullPath: '/api/lord/file'
      preLoaderRoute: typeof ApiLordFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/automation': {
      id: '/api/lord/automation'
      path: '/api/lord/automation'
      fullPath: '/api/lord/automation'
      preLoaderRoute: typeof ApiLordAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/activity': {
      id: '/api/lord/activity'
      path: '/api/lord/activity'
      fullPath: '/api/lord/activity'
      preLoaderRoute: typeof ApiLordActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/whiteboard': {
      id: '/api/learning/whiteboard'
      path: '/api/learning/whiteboard'
      fullPath: '/api/learning/whiteboard'
      preLoaderRoute: typeof ApiLearningWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/voice': {
      id: '/api/learning/voice'
      path: '/api/learning/voice'
      fullPath: '/api/learning/voice'
      preLoaderRoute: typeof ApiLearningVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/session': {
      id: '/api/learning/session'
      path: '/api/learning/session'
      fullPath: '/api/learning/session'
      preLoaderRoute: typeof ApiLearningSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/revision': {
      id: '/api/learning/revision'
      path: '/api/learning/revision'
      fullPath: '/api/learning/revision'
      preLoaderRoute: typeof ApiLearningRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/ocr': {
      id: '/api/learning/ocr'
      path: '/api/learning/ocr'
      fullPath: '/api/learning/ocr'
      preLoaderRoute: typeof ApiLearningOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/notes': {
      id: '/api/learning/notes'
      path: '/api/learning/notes'
      fullPath: '/api/learning/notes'
      preLoaderRoute: typeof ApiLearningNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/memory': {
      id: '/api/learning/memory'
      path: '/api/learning/memory'
      fullPath: '/api/learning/memory'
      preLoaderRoute: typeof ApiLearningMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/goals': {
      id: '/api/learning/goals'
      path: '/api/learning/goals'
      fullPath: '/api/learning/goals'
      preLoaderRoute: typeof ApiLearningGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/flashcards': {
      id: '/api/learning/flashcards'
      path: '/api/learning/flashcards'
      fullPath: '/api/learning/flashcards'
      preLoaderRoute: typeof ApiLearningFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/features': {
      id: '/api/learning/features'
      path: '/api/learning/features'
      fullPath: '/api/learning/features'
      preLoaderRoute: typeof ApiLearningFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/exams': {
      id: '/api/learning/exams'
      path: '/api/learning/exams'
      fullPath: '/api/learning/exams'
      preLoaderRoute: typeof ApiLearningExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/analytics': {
      id: '/api/learning/analytics'
      path: '/api/learning/analytics'
      fullPath: '/api/learning/analytics'
      preLoaderRoute: typeof ApiLearningAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge2/relations': {
      id: '/api/knowledge2/relations'
      path: '/api/knowledge2/relations'
      fullPath: '/api/knowledge2/relations'
      preLoaderRoute: typeof ApiKnowledge2RelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge2/entities': {
      id: '/api/knowledge2/entities'
      path: '/api/knowledge2/entities'
      fullPath: '/api/knowledge2/entities'
      preLoaderRoute: typeof ApiKnowledge2EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/upload': {
      id: '/api/knowledge/upload'
      path: '/api/knowledge/upload'
      fullPath: '/api/knowledge/upload'
      preLoaderRoute: typeof ApiKnowledgeUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/$id': {
      id: '/api/knowledge/$id'
      path: '/api/knowledge/$id'
      fullPath: '/api/knowledge/$id'
      preLoaderRoute: typeof ApiKnowledgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/regenerate': {
      id: '/api/images/regenerate'
      path: '/regenerate'
      fullPath: '/api/images/regenerate'
      preLoaderRoute: typeof ApiImagesRegenerateRouteImport
      parentRoute: typeof ApiImagesRoute
    }
    '/api/images/models': {
      id: '/api/images/models'
      path: '/models'
      fullPath: '/api/images/models'
      preLoaderRoute: typeof ApiImagesModelsRouteImport
      parentRoute: typeof ApiImagesRoute
    }
    '/api/images/$id': {
      id: '/api/images/$id'
      path: '/$id'
      fullPath: '/api/images/$id'
      preLoaderRoute: typeof ApiImagesIdRouteImport
      parentRoute: typeof ApiImagesRoute
    }
    '/api/image/health': {
      id: '/api/image/health'
      path: '/api/image/health'
      fullPath: '/api/image/health'
      preLoaderRoute: typeof ApiImageHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/command-palette/search': {
      id: '/api/command-palette/search'
      path: '/api/command-palette/search'
      fullPath: '/api/command-palette/search'
      preLoaderRoute: typeof ApiCommandPaletteSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/versions': {
      id: '/api/canvas/versions'
      path: '/api/canvas/versions'
      fullPath: '/api/canvas/versions'
      preLoaderRoute: typeof ApiCanvasVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/stream': {
      id: '/api/canvas/stream'
      path: '/api/canvas/stream'
      fullPath: '/api/canvas/stream'
      preLoaderRoute: typeof ApiCanvasStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/context': {
      id: '/api/brain/context'
      path: '/api/brain/context'
      fullPath: '/api/brain/context'
      preLoaderRoute: typeof ApiBrainContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gateway': {
      id: '/api/admin/gateway'
      path: '/api/admin/gateway'
      fullPath: '/api/admin/gateway'
      preLoaderRoute: typeof ApiAdminGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center/vision': {
      id: '/_authenticated/command-center/vision'
      path: '/vision'
      fullPath: '/command-center/vision'
      preLoaderRoute: typeof AuthenticatedCommandCenterVisionRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/smart-home': {
      id: '/_authenticated/command-center/smart-home'
      path: '/smart-home'
      fullPath: '/command-center/smart-home'
      preLoaderRoute: typeof AuthenticatedCommandCenterSmartHomeRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/settings': {
      id: '/_authenticated/command-center/settings'
      path: '/settings'
      fullPath: '/command-center/settings'
      preLoaderRoute: typeof AuthenticatedCommandCenterSettingsRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/pc': {
      id: '/_authenticated/command-center/pc'
      path: '/pc'
      fullPath: '/command-center/pc'
      preLoaderRoute: typeof AuthenticatedCommandCenterPcRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/office': {
      id: '/_authenticated/command-center/office'
      path: '/office'
      fullPath: '/command-center/office'
      preLoaderRoute: typeof AuthenticatedCommandCenterOfficeRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/mobile': {
      id: '/_authenticated/command-center/mobile'
      path: '/mobile'
      fullPath: '/command-center/mobile'
      preLoaderRoute: typeof AuthenticatedCommandCenterMobileRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/files': {
      id: '/_authenticated/command-center/files'
      path: '/files'
      fullPath: '/command-center/files'
      preLoaderRoute: typeof AuthenticatedCommandCenterFilesRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/browser': {
      id: '/_authenticated/command-center/browser'
      path: '/browser'
      fullPath: '/command-center/browser'
      preLoaderRoute: typeof AuthenticatedCommandCenterBrowserRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/command-center/automations': {
      id: '/_authenticated/command-center/automations'
      path: '/automations'
      fullPath: '/command-center/automations'
      preLoaderRoute: typeof AuthenticatedCommandCenterAutomationsRouteImport
      parentRoute: typeof AuthenticatedCommandCenterRouteRoute
    }
    '/_authenticated/canvas/$id': {
      id: '/_authenticated/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof AuthenticatedCanvasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/lord/vision/webcam': {
      id: '/api/lord/vision/webcam'
      path: '/api/lord/vision/webcam'
      fullPath: '/api/lord/vision/webcam'
      preLoaderRoute: typeof ApiLordVisionWebcamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/vision/screen': {
      id: '/api/lord/vision/screen'
      path: '/api/lord/vision/screen'
      fullPath: '/api/lord/vision/screen'
      preLoaderRoute: typeof ApiLordVisionScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/office/powerpoint': {
      id: '/api/lord/office/powerpoint'
      path: '/api/lord/office/powerpoint'
      fullPath: '/api/lord/office/powerpoint'
      preLoaderRoute: typeof ApiLordOfficePowerpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/office/excel': {
      id: '/api/lord/office/excel'
      path: '/api/lord/office/excel'
      fullPath: '/api/lord/office/excel'
      preLoaderRoute: typeof ApiLordOfficeExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/mobile/status': {
      id: '/api/lord/mobile/status'
      path: '/api/lord/mobile/status'
      fullPath: '/api/lord/mobile/status'
      preLoaderRoute: typeof ApiLordMobileStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/mobile/pair': {
      id: '/api/lord/mobile/pair'
      path: '/api/lord/mobile/pair'
      fullPath: '/api/lord/mobile/pair'
      preLoaderRoute: typeof ApiLordMobilePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/iot/devices': {
      id: '/api/lord/iot/devices'
      path: '/api/lord/iot/devices'
      fullPath: '/api/lord/iot/devices'
      preLoaderRoute: typeof ApiLordIotDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/browser/action': {
      id: '/api/lord/browser/action'
      path: '/api/lord/browser/action'
      fullPath: '/api/lord/browser/action'
      preLoaderRoute: typeof ApiLordBrowserActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/agent/stop': {
      id: '/api/lord/agent/stop'
      path: '/api/lord/agent/stop'
      fullPath: '/api/lord/agent/stop'
      preLoaderRoute: typeof ApiLordAgentStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lord/agent/execute': {
      id: '/api/lord/agent/execute'
      path: '/api/lord/agent/execute'
      fullPath: '/api/lord/agent/execute'
      preLoaderRoute: typeof ApiLordAgentExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/sources/ingest': {
      id: '/api/learning/sources/ingest'
      path: '/api/learning/sources/ingest'
      fullPath: '/api/learning/sources/ingest'
      preLoaderRoute: typeof ApiLearningSourcesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-plans/$id/tasks/': {
      id: '/api/study-plans/$id/tasks/'
      path: '/tasks'
      fullPath: '/api/study-plans/$id/tasks/'
      preLoaderRoute: typeof ApiStudyPlansIdTasksIndexRouteImport
      parentRoute: typeof ApiStudyPlansIdRoute
    }
    '/api/research/$id/sources/': {
      id: '/api/research/$id/sources/'
      path: '/api/research/$id/sources'
      fullPath: '/api/research/$id/sources/'
      preLoaderRoute: typeof ApiResearchIdSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-plans/$id/tasks/$taskId': {
      id: '/api/study-plans/$id/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/api/study-plans/$id/tasks/$taskId'
      preLoaderRoute: typeof ApiStudyPlansIdTasksTaskIdRouteImport
      parentRoute: typeof ApiStudyPlansIdRoute
    }
    '/api/study-plans/$id/ai/suggest': {
      id: '/api/study-plans/$id/ai/suggest'
      path: '/ai/suggest'
      fullPath: '/api/study-plans/$id/ai/suggest'
      preLoaderRoute: typeof ApiStudyPlansIdAiSuggestRouteImport
      parentRoute: typeof ApiStudyPlansIdRoute
    }
    '/api/study-plans/$id/ai/optimize': {
      id: '/api/study-plans/$id/ai/optimize'
      path: '/ai/optimize'
      fullPath: '/api/study-plans/$id/ai/optimize'
      preLoaderRoute: typeof ApiStudyPlansIdAiOptimizeRouteImport
      parentRoute: typeof ApiStudyPlansIdRoute
    }
    '/api/study-plans/$id/ai/generate': {
      id: '/api/study-plans/$id/ai/generate'
      path: '/ai/generate'
      fullPath: '/api/study-plans/$id/ai/generate'
      preLoaderRoute: typeof ApiStudyPlansIdAiGenerateRouteImport
      parentRoute: typeof ApiStudyPlansIdRoute
    }
    '/api/lord/iot/device/action': {
      id: '/api/lord/iot/device/action'
      path: '/api/lord/iot/device/action'
      fullPath: '/api/lord/iot/device/action'
      preLoaderRoute: typeof ApiLordIotDeviceActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCommandCenterRouteRouteChildren {
  AuthenticatedCommandCenterAutomationsRoute: typeof AuthenticatedCommandCenterAutomationsRoute
  AuthenticatedCommandCenterBrowserRoute: typeof AuthenticatedCommandCenterBrowserRoute
  AuthenticatedCommandCenterFilesRoute: typeof AuthenticatedCommandCenterFilesRoute
  AuthenticatedCommandCenterMobileRoute: typeof AuthenticatedCommandCenterMobileRoute
  AuthenticatedCommandCenterOfficeRoute: typeof AuthenticatedCommandCenterOfficeRoute
  AuthenticatedCommandCenterPcRoute: typeof AuthenticatedCommandCenterPcRoute
  AuthenticatedCommandCenterSettingsRoute: typeof AuthenticatedCommandCenterSettingsRoute
  AuthenticatedCommandCenterSmartHomeRoute: typeof AuthenticatedCommandCenterSmartHomeRoute
  AuthenticatedCommandCenterVisionRoute: typeof AuthenticatedCommandCenterVisionRoute
  AuthenticatedCommandCenterIndexRoute: typeof AuthenticatedCommandCenterIndexRoute
}

const AuthenticatedCommandCenterRouteRouteChildren: AuthenticatedCommandCenterRouteRouteChildren =
  {
    AuthenticatedCommandCenterAutomationsRoute:
      AuthenticatedCommandCenterAutomationsRoute,
    AuthenticatedCommandCenterBrowserRoute:
      AuthenticatedCommandCenterBrowserRoute,
    AuthenticatedCommandCenterFilesRoute: AuthenticatedCommandCenterFilesRoute,
    AuthenticatedCommandCenterMobileRoute:
      AuthenticatedCommandCenterMobileRoute,
    AuthenticatedCommandCenterOfficeRoute:
      AuthenticatedCommandCenterOfficeRoute,
    AuthenticatedCommandCenterPcRoute: AuthenticatedCommandCenterPcRoute,
    AuthenticatedCommandCenterSettingsRoute:
      AuthenticatedCommandCenterSettingsRoute,
    AuthenticatedCommandCenterSmartHomeRoute:
      AuthenticatedCommandCenterSmartHomeRoute,
    AuthenticatedCommandCenterVisionRoute:
      AuthenticatedCommandCenterVisionRoute,
    AuthenticatedCommandCenterIndexRoute: AuthenticatedCommandCenterIndexRoute,
  }

const AuthenticatedCommandCenterRouteRouteWithChildren =
  AuthenticatedCommandCenterRouteRoute._addFileChildren(
    AuthenticatedCommandCenterRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandCenterRouteRoute: typeof AuthenticatedCommandCenterRouteRouteWithChildren
  AuthenticatedBoardsRoute: typeof AuthenticatedBoardsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProductivityRoute: typeof AuthenticatedProductivityRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedCanvasIdRoute: typeof AuthenticatedCanvasIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedCanvasIndexRoute: typeof AuthenticatedCanvasIndexRoute
  AuthenticatedDashboardsIndexRoute: typeof AuthenticatedDashboardsIndexRoute
  AuthenticatedKnowledge2IndexRoute: typeof AuthenticatedKnowledge2IndexRoute
  AuthenticatedObservabilityIndexRoute: typeof AuthenticatedObservabilityIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandCenterRouteRoute:
    AuthenticatedCommandCenterRouteRouteWithChildren,
  AuthenticatedBoardsRoute: AuthenticatedBoardsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProductivityRoute: AuthenticatedProductivityRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedCanvasIdRoute: AuthenticatedCanvasIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedCanvasIndexRoute: AuthenticatedCanvasIndexRoute,
  AuthenticatedDashboardsIndexRoute: AuthenticatedDashboardsIndexRoute,
  AuthenticatedKnowledge2IndexRoute: AuthenticatedKnowledge2IndexRoute,
  AuthenticatedObservabilityIndexRoute: AuthenticatedObservabilityIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiImagesRouteChildren {
  ApiImagesIdRoute: typeof ApiImagesIdRoute
  ApiImagesModelsRoute: typeof ApiImagesModelsRoute
  ApiImagesRegenerateRoute: typeof ApiImagesRegenerateRoute
}

const ApiImagesRouteChildren: ApiImagesRouteChildren = {
  ApiImagesIdRoute: ApiImagesIdRoute,
  ApiImagesModelsRoute: ApiImagesModelsRoute,
  ApiImagesRegenerateRoute: ApiImagesRegenerateRoute,
}

const ApiImagesRouteWithChildren = ApiImagesRoute._addFileChildren(
  ApiImagesRouteChildren,
)

interface ApiSharesRouteChildren {
  ApiSharesTokenRoute: typeof ApiSharesTokenRoute
}

const ApiSharesRouteChildren: ApiSharesRouteChildren = {
  ApiSharesTokenRoute: ApiSharesTokenRoute,
}

const ApiSharesRouteWithChildren = ApiSharesRoute._addFileChildren(
  ApiSharesRouteChildren,
)

interface ApiStudyPlansIdRouteChildren {
  ApiStudyPlansIdAiGenerateRoute: typeof ApiStudyPlansIdAiGenerateRoute
  ApiStudyPlansIdAiOptimizeRoute: typeof ApiStudyPlansIdAiOptimizeRoute
  ApiStudyPlansIdAiSuggestRoute: typeof ApiStudyPlansIdAiSuggestRoute
  ApiStudyPlansIdTasksTaskIdRoute: typeof ApiStudyPlansIdTasksTaskIdRoute
  ApiStudyPlansIdTasksIndexRoute: typeof ApiStudyPlansIdTasksIndexRoute
}

const ApiStudyPlansIdRouteChildren: ApiStudyPlansIdRouteChildren = {
  ApiStudyPlansIdAiGenerateRoute: ApiStudyPlansIdAiGenerateRoute,
  ApiStudyPlansIdAiOptimizeRoute: ApiStudyPlansIdAiOptimizeRoute,
  ApiStudyPlansIdAiSuggestRoute: ApiStudyPlansIdAiSuggestRoute,
  ApiStudyPlansIdTasksTaskIdRoute: ApiStudyPlansIdTasksTaskIdRoute,
  ApiStudyPlansIdTasksIndexRoute: ApiStudyPlansIdTasksIndexRoute,
}

const ApiStudyPlansIdRouteWithChildren = ApiStudyPlansIdRoute._addFileChildren(
  ApiStudyPlansIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImagesRoute: ApiImagesRouteWithChildren,
  ApiOpenrouterTestRoute: ApiOpenrouterTestRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSharesRoute: ApiSharesRouteWithChildren,
  ApiTitleRoute: ApiTitleRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAdminGatewayRoute: ApiAdminGatewayRoute,
  ApiBrainContextRoute: ApiBrainContextRoute,
  ApiCanvasStreamRoute: ApiCanvasStreamRoute,
  ApiCanvasVersionsRoute: ApiCanvasVersionsRoute,
  ApiCommandPaletteSearchRoute: ApiCommandPaletteSearchRoute,
  ApiImageHealthRoute: ApiImageHealthRoute,
  ApiKnowledgeIdRoute: ApiKnowledgeIdRoute,
  ApiKnowledgeUploadRoute: ApiKnowledgeUploadRoute,
  ApiKnowledge2EntitiesRoute: ApiKnowledge2EntitiesRoute,
  ApiKnowledge2RelationsRoute: ApiKnowledge2RelationsRoute,
  ApiLearningAnalyticsRoute: ApiLearningAnalyticsRoute,
  ApiLearningExamsRoute: ApiLearningExamsRoute,
  ApiLearningFeaturesRoute: ApiLearningFeaturesRoute,
  ApiLearningFlashcardsRoute: ApiLearningFlashcardsRoute,
  ApiLearningGoalsRoute: ApiLearningGoalsRoute,
  ApiLearningMemoryRoute: ApiLearningMemoryRoute,
  ApiLearningNotesRoute: ApiLearningNotesRoute,
  ApiLearningOcrRoute: ApiLearningOcrRoute,
  ApiLearningRevisionRoute: ApiLearningRevisionRoute,
  ApiLearningSessionRoute: ApiLearningSessionRoute,
  ApiLearningVoiceRoute: ApiLearningVoiceRoute,
  ApiLearningWhiteboardRoute: ApiLearningWhiteboardRoute,
  ApiLordActivityRoute: ApiLordActivityRoute,
  ApiLordAutomationRoute: ApiLordAutomationRoute,
  ApiLordFileRoute: ApiLordFileRoute,
  ApiLordFilesRoute: ApiLordFilesRoute,
  ApiLordStatusRoute: ApiLordStatusRoute,
  ApiLordToolRoute: ApiLordToolRoute,
  ApiObservabilityHealthRoute: ApiObservabilityHealthRoute,
  ApiProjectsIdRoute: ApiProjectsIdRoute,
  ApiSharedTokenRoute: ApiSharedTokenRoute,
  ApiStudyPlansIdRoute: ApiStudyPlansIdRouteWithChildren,
  ApiCanvasIndexRoute: ApiCanvasIndexRoute,
  ApiDashboardsIndexRoute: ApiDashboardsIndexRoute,
  ApiKnowledgeIndexRoute: ApiKnowledgeIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiStudyPlansIndexRoute: ApiStudyPlansIndexRoute,
  ApiLearningSourcesIngestRoute: ApiLearningSourcesIngestRoute,
  ApiLordAgentExecuteRoute: ApiLordAgentExecuteRoute,
  ApiLordAgentStopRoute: ApiLordAgentStopRoute,
  ApiLordBrowserActionRoute: ApiLordBrowserActionRoute,
  ApiLordIotDevicesRoute: ApiLordIotDevicesRoute,
  ApiLordMobilePairRoute: ApiLordMobilePairRoute,
  ApiLordMobileStatusRoute: ApiLordMobileStatusRoute,
  ApiLordOfficeExcelRoute: ApiLordOfficeExcelRoute,
  ApiLordOfficePowerpointRoute: ApiLordOfficePowerpointRoute,
  ApiLordVisionScreenRoute: ApiLordVisionScreenRoute,
  ApiLordVisionWebcamRoute: ApiLordVisionWebcamRoute,
  ApiLordIotDeviceActionRoute: ApiLordIotDeviceActionRoute,
  ApiResearchIdSourcesIndexRoute: ApiResearchIdSourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
