// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

async function getAuthenticatedSupabase(request: Request) {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY", "SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!request?.headers) {
    throw new Error("Unauthorized: No request headers available");
  }

  let authContext: {
    supabase: SupabaseClient<Database>;
    userId: string;
    claims: unknown;
  };

  // Try to get user from Authorization header first
  const authHeader = request.headers.get("authorization");
  if (authHeader) {
    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getUser();
    if (error || !data?.user) {
      throw new Error("Unauthorized: Invalid token");
    }

    const userId = data.user.id;
    if (!userId) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    authContext = {
      supabase,
      userId,
      claims: data.user,
    };
  } else {
    // No Authorization header; use session cookie
    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        // We don't set any headers; session is managed via cookie
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
    if (sessionError || !sessionData?.session) {
      throw new Error("Unauthorized: Invalid session");
    }

    authContext = {
      supabase,
      userId: sessionData.session.user.id,
      claims: sessionData.session.user,
    };
  }

  return {
    supabase: authContext.supabase,
    userId: authContext.userId,
    claims: authContext.claims,
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();
    const authContext = await getAuthenticatedSupabase(request);

    return next({
      context: authContext,
    });
  },
);

export const requireSupabaseRequestAuth = createMiddleware({ type: "request" }).server(
  async ({ request, next }) => {
    const path = new URL(request.url).pathname;
    console.info(JSON.stringify({ event: "auth_start", message: "AUTH START", path }));
    try {
      const authContext = await getAuthenticatedSupabase(request);
      console.info(
        JSON.stringify({ event: "auth_ok", message: "AUTH OK", path, userId: authContext.userId }),
      );
      return next({
        context: authContext,
      });
    } catch (error) {
      console.error("ERROR", error);
      console.error("STACK TRACE", error instanceof Error ? error.stack : undefined);
      // Request middleware is used by JSON API routes. Returning a response
      // here prevents auth failures from escaping into the global HTML error
      // boundary and turning an expected 401 into a misleading 500 page.
      return Response.json(
        {
          error: {
            code: "AI_AUTH_ERROR",
            message: "Sign in to use this feature.",
            requestId: crypto.randomUUID(),
          },
        },
        { status: 401, headers: { "Cache-Control": "no-store" } },
      );
    }
  },
);
